---
- hosts: localhost
  # We run the commands on local; 
  connection: local
  # Enable sudo
  become: true

  tasks:
  - name: install packages
    package:
      name: 
        - htop
        - tmux
        - vim-nox

  
      

